// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RMS.Models;

#nullable disable

namespace RMS.Migrations
{
    [DbContext(typeof(dbRMSContext))]
    [Migration("20240909072749_UpdateEqptissueSchema")]
    partial class UpdateEqptissueSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RMS.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("active")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Branch");
                });

            modelBuilder.Entity("RMS.Models.Eqptissue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EqptnameId")
                        .HasColumnType("int");

                    b.Property<bool?>("active")
                        .HasColumnType("bit");

                    b.Property<int?>("branchid")
                        .HasColumnType("int");

                    b.Property<DateTime?>("date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("eqptid")
                        .HasColumnType("int");

                    b.Property<int?>("qty")
                        .HasColumnType("int");

                    b.Property<string>("remarks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EqptnameId");

                    b.HasIndex("branchid");

                    b.ToTable("Eqptissue");
                });

            modelBuilder.Entity("RMS.Models.Eqptname", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("active")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Eqptname");
                });

            modelBuilder.Entity("RMS.Models.Eqptstore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EqptnameId")
                        .HasColumnType("int");

                    b.Property<bool?>("active")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("eqptid")
                        .HasColumnType("int");

                    b.Property<int?>("qty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EqptnameId");

                    b.ToTable("Eqptstore");
                });

            modelBuilder.Entity("RMS.Models.Eqptissue", b =>
                {
                    b.HasOne("RMS.Models.Eqptname", "Eqptname")
                        .WithMany()
                        .HasForeignKey("EqptnameId");

                    b.HasOne("RMS.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("branchid");

                    b.Navigation("Branch");

                    b.Navigation("Eqptname");
                });

            modelBuilder.Entity("RMS.Models.Eqptstore", b =>
                {
                    b.HasOne("RMS.Models.Eqptname", "Eqptname")
                        .WithMany()
                        .HasForeignKey("EqptnameId");

                    b.Navigation("Eqptname");
                });
#pragma warning restore 612, 618
        }
    }
}
